name: Laravel Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        include:
          - php: '8.2'
            laravel: '10.*'
          - php: '8.3'
            laravel: '10.*'
          - php: '8.4'
            laravel: '10.*'
          - php: '8.5'
            laravel: '10.*'
          - php: '8.2'
            laravel: '11.*'
          - php: '8.3'
            laravel: '11.*'
          - php: '8.4'
            laravel: '11.*'
          - php: '8.5'
            laravel: '11.*'
          - php: '8.2'
            laravel: '12.*'
          - php: '8.3'
            laravel: '12.*'
          - php: '8.4'
            laravel: '12.*'
          - php: '8.5'
            laravel: '12.*'
          - php: '8.3'
            laravel: '13.*'
          - php: '8.4'
            laravel: '13.*'
          - php: '8.5'
            laravel: '13.*'

    name: P${{ matrix.php }} - L${{ matrix.laravel }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip
          tools: composer:v2
          coverage: none

      - name: Install dependencies
        run: |
          case "${{ matrix.laravel }}" in
            "10.*")
              TESTBENCH=">=8.13.0 <9.0"
              PEST=">=2.0 <3.0"
              PEST_ARCH=">=2.0 <3.0"
              PEST_LARAVEL=">=2.0 <3.0"
              ;;
            "11.*")
              TESTBENCH=">=9.0 <10.0"
              PEST=">=3.7 <4.0"
              PEST_ARCH=">=3.0 <4.0"
              PEST_LARAVEL=">=3.1 <4.0"
              ;;
            "12.*")
              TESTBENCH=">=10.0 <11.0"
              PEST=">=3.7 <4.0"
              PEST_ARCH=">=3.0 <4.0"
              PEST_LARAVEL=">=3.1 <4.0"
              ;;
            "13.*")
              TESTBENCH=">=11.0 <12.0"
              PEST=">=4.4.1 <5.0"
              PEST_ARCH=">=4.0 <5.0"
              PEST_LARAVEL=">=4.1 <5.0"
              ;;
          esac

          composer require "illuminate/console:${{ matrix.laravel }}" "illuminate/contracts:${{ matrix.laravel }}" "illuminate/support:${{ matrix.laravel }}" --no-interaction --no-update
          composer require "orchestra/testbench:${TESTBENCH}" "pestphp/pest:${PEST}" "pestphp/pest-plugin-arch:${PEST_ARCH}" "pestphp/pest-plugin-laravel:${PEST_LARAVEL}" --dev --no-interaction --no-update
          composer update --prefer-stable --prefer-dist --no-interaction --no-progress

      - name: Execute tests
        run: vendor/bin/pest --no-coverage
